### ISSUE TITLE
Error 0xc0000142 after using this dnperf

### ISSUE THREAD

**Issue by yuenming666** [dnblank123/dnperf-public#2]
any solution? I use netapi.dll/dnperf without another mod/dll file

**Comment by dnblank123** [comment]
Hi, @yuenming666, I'll try to update it this day or tomorrow

**Comment by yuenming666** [comment]
i'm using windows 11 23h2, OS Build 22631,4541
what server? you mean country or something else?

**Comment by dnblank123** [comment]
@yuenming666 game server, example: Dragon Nest "Sea"

**Comment by dnblank123** [comment]
@yuenming666 can you try this
[netapi32.zip](https://github.com/user-attachments/files/18050896/netapi32.zip)

**Comment by yuenming666** [comment]
ill try once I reach home, thanks!

**Comment by yuenming666** [comment]
@dnblank123 hello sir!, I try it just now, the error 0xc0000142 still there, I'm using Intel CPU
I already install all directx version, visual c++ , netframework but the error still there

**Comment by dnblank123** [comment]
@yuenming666 
[netapi32.zip](https://github.com/user-attachments/files/18051117/netapi32.zip)

**Comment by yuenming666** [comment]
@dnblank123 same issue still happened, do u think there is somethign wrong with my PC? or bcz I'm using Intel CPU?

**Comment by dnblank123** [comment]
tbh idk, unless I attach a debugger. I already attached a debugger on mine, and theres no breaks (crashes). Also one of my guildmate already used this on Windows 10 + Intel CPU, so might be related to Windows 11 that im not aware of.

**Comment by yuenming666** [comment]
did u using w10? suck to be w11 :(

**Comment by dnblank123** [comment]
> did u using w10? suck to be w11 :(

Im using W10.

**Comment by yuenming666** [comment]
i'm going to downgrade to w10 next time, I just trying w11 like few month ago xd
thank you for sharing, god bless you ~! <3

**Comment by dnblank123** [comment]
@yuenming666 I tried VM using Windows 11 (AMD CPU), the game launches normally

**Comment by yuenming666** [comment]
@dnblank123 guess windows11 with intel is problem

**Comment by dnblank123** [comment]
nvm I think I forgot to turn off -march=native, I'll send a new one without it

**Comment by dnblank123** [comment]
this should now work [netapi32.zip](https://github.com/user-attachments/files/18051856/netapi32.zip)

**Comment by yuenming666** [comment]
![image](https://github.com/user-attachments/assets/45360279-c196-4c98-84c1-aca0594dbb9d)
still same issue

**Comment by yuenming666** [comment]
![image](https://github.com/user-attachments/assets/d0174666-95a6-48ab-a3ba-8161c68f2992)
![image](https://github.com/user-attachments/assets/ec842b26-406b-4494-b8bc-ccc50081b357)
![image](https://github.com/user-attachments/assets/8ff629b9-af14-477a-bd80-3503a8c78b27)

**Comment by dnblank123** [comment]
Oh, your CPU doesnt have AVX.

**Comment by yuenming666** [comment]
so it doesnt work to cpu that dont have AVX?

**Comment by dnblank123** [comment]
> so it doesnt work to cpu that dont have AVX?

Yeah, but I might exclude some features so non-AVX CPU can still use the dll

**Comment by yuenming666** [comment]
ohh, sad
okayyy thank you so much

**Comment by dnblank123** [comment]
@yuenming666 can you try [netapi32.zip](https://github.com/user-attachments/files/18133970/netapi32.zip)

**Comment by yuenming666** [comment]
@dnblank123 the error is disappear, but the new issue is come when I put the netapi32.dll and I start the launcher, the XIGNCODE not appear, when I try to take off the netapi32.dll the XIGNCODE work normal like usual

**Comment by yuenming666** [comment]
![image](https://github.com/user-attachments/assets/a0bb06ee-36fa-409d-9625-58c7651f6d6f)
Still with same device, but I downgrade to W10 from W11

**Comment by dnblank123** [comment]
@yuenming666 [netapi32.zip](https://github.com/user-attachments/files/18134338/netapi32.zip)

**Comment by dnblank123** [comment]
@yuenming666 [netapi32.zip](https://github.com/user-attachments/files/18134368/netapi32.zip)

**Comment by yuenming666** [comment]
@dnblank123 Same issue sir, I even try restart my computer  and the xigncode still not appear

**Comment by dnblank123** [comment]
@yuenming666 [netapi32.zip](https://github.com/user-attachments/files/18134497/netapi32.zip)
if this still not works, I'll be closing the issue, since you lack a lot of CPU features tbh.

**Comment by yuenming666** [comment]
@dnblank123 I finally can run the game with the last build netapi32.dll thank you so much for all your help and effort I really appreciate it, and also may I know what feature that I can get from this netapi knowing I lack a lot of feature due old CPU

**Comment by dnblank123** [comment]
you'll still have these stuff, but the performance might be negligible on some C (SIMD) functions:
https://github.com/dnblank123/dnperf-public?tab=readme-ov-file#list-of-changes
https://github.com/dnblank123/dnperf-public?tab=readme-ov-file#upcoming-releases
and the CPU features what I meant are AVX, AVX2 etc.

**Comment by yuenming666** [comment]
alright got it, thank you so muchhh! <3
